#!/bin/bash

scp server.jar 10:/home/servisofts/servicios/calistenia/entornos/calistenia/servicios/calistenia/
# ssh 10 'cd ~/servicios/CasaGrande/ && ./servisofts.sh down'
# ssh 10 'cd ~/servicios/CasaGrande/ && ./servisofts.sh up -d'